### ISSUE TITLE
windows cant list files or find quarantine.tar

### ISSUE THREAD

**Issue by Zedroid** [knez/defender-dump#3]
C:\Users\zedro\Downloads>py  C:\Users\zedro\Downloads\defender-dump.py c:/
Traceback (most recent call last):
  File "C:\Users\zedro\Downloads\defender-dump.py", line 182, in <module>
    main(parser.parse_args())
  File "C:\Users\zedro\Downloads\defender-dump.py", line 165, in main
    detection_max_len = max([len(x[2]) for x in entries])
ValueError: max() arg is an empty sequence

i did --dump and it said it did the quarnatine.tar but i cannot find it in the folder of the py script is in

**Comment by m-terlinde** [comment]
Sorry to necro-post, but I ran into the same issue. The solution was rather simple: run the command with admin rights.
The components used in the script swallow access rights errors.
